<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerB0m3VCF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerB0m3VCF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerB0m3VCF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerB0m3VCF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerB0m3VCF\App_KernelDevDebugContainer([
    'container.build_hash' => 'B0m3VCF',
    'container.build_id' => '87884b8f',
    'container.build_time' => 1659402054,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerB0m3VCF');
